# Dependencies
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty


# Setup
title:            Reasonable Deviations
tagline:          'another science blog'
description:      'into the subjects of maths, physics, finance, and computer science'
baseurl:          /ReasonableDeviations/
imageurl:       '/ReasonableDeviations/assets/images/'

author:
  name:           'Robert Andrew Martin'
  url:            https://twitter.com/mdo
  email:        'martin.robertandrew@gmail.com'


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/surelyourejoking
