# Dependencies
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty


# Setup
title:            Reasonable Deviations
tagline:          'a rational approach to complexity'
description:      'a rational approach to complexity'
url:               'https://reasonabledeviations.science'
baseurl:          
imageurl:       '/assets/images/'

author:
  name:           'Robert Andrew Martin'
  email:        'martin.robertandrew@gmail.com'




# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/robertmartin8

social:
    linkedin: https://www.linkedin.com/in/robert-a-martin/

# Structure
paginate:         3

collections:
  notes:
      output: true
      permalink: /notes/:path/
